os:
  - linux

dist: trusty

language: java

services:
  - docker

jdk:
  - oraclejdk9

env:
  - TRAVIS_NODE_VERSION="9"

git:
  depth: false

addons:
  sonarcloud:
    organization: "maibornwolff"
    token:
      secure: $SONAR_TOKEN

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wine
  - chmod +x ./analysis/gradlew

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - cd visualization; npm install; cd ..

script:
  - cd visualization; npm run build:web
  - cd analysis; ./gradlew build

jobs:
  fast_finish: true
  include:
    - stage: test
      name: "Visualization Unit Test and Linter"
      before_script: cd visualization
      script:
        - npm run test --ci
        - npm run lint
    - name: "Visualization E2E Test"
      script: cd visualization; npm run e2e --ci
    - name: "Analysis Integration Test"
      before_script:
        - chmod +x ./analysis/gradlew
        - cd analysis
      script:
        - ./gradlew integrationTest

    - stage: sonar
      name: "Publishes visualization sonar results"
      script: skip
      deploy:
        - provider: script
          script: ./visualization/script/sonar-publish.sh
          cleanup: true

    - name: "Publishes analysis sonar results"
      script: skip
      deploy:
        - provider: script
          script: ./analysis/script/sonar-publish.sh
          cleanup: true

    - stage: deploy
      script: skip
      deploy:
        # releases the built packages on github when a commit is tagged
        - provider: releases
          script: cd visualization; npm run package
          api_key: $GITHUB_TOKEN
          file_glob: true
          file:
            - "visualization/dist/packages/*.zip"
            - "analysis/build/distributions/*.tar"
          cleanup: true
          on:
            tags: true
            branch: master

        # publishes visualization npm package
        - provider: script
          script: ./visualization/script/npm-publish.sh
          cleanup: true
          on:
            tags: true
            branch: master

        # publishes analysis npm package
        - provider: script
          script: ./analysis/script/npm-publish.sh
          cleanup: true
          on:
            tags: true
            branch: master

        # commits the gh-pages directory to the gh-pages branch. Does not ignore built ressources
        - provider: pages
          script:
            - cd visualization; docker build -t maibornwolff/codecharta-visualization .
            - ./script/build_gh_pages.sh
          github_token: $GITHUB_TOKEN
          cleanup: true
          local_dir: "gh-pages"
          on:
            tags: true
            branch: master

        # publishes visualization docker image
        - provider: script
          script: ./visualization/script/docker-publish.sh
          cleanup: true
          on:
            tags: true
            branch: master

stages:
  - test
  - name: sonar
    if: branch = master AND type != pull_request
  - name: deploy
    if: tag IS present

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - ./visualization/node_modules/nwjs-builder-phoenix/caches/
