name: Release Gh-Pages

on: 
  push: 
    tags: 'v*'

jobs:  
  build_project:
    name: Build Project

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with: 
          java-version: '11'
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'  
      
      - name: Build analysis
        working-directory: ./analysis
        run: chmod +x ./gradlew
          
      - name: Build visualization
        run: sh ./visualization/script/travis-build.sh     
        
      - name: Run building script build gh pages
        run: sh ./script/build_gh_pages.sh   

      - name: Upload Release Files to tagged release
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["visualization/dist/packages/*.zip", "analysis/build/distributions/*.tar"]'
          
  
